---
driver:
  name: docker

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  require_chef_for_busser: false


platforms:
  - name: ubuntu-14
    driver_config:
            image: ansible:xenial
            platform: ubuntu
    driver_config:
            image: centos:6
            platform: centos
  - name: ubuntu-16
    driver_config:
            image: ubuntu:trusty
            platform: ubuntu
  - name: centos-7
    driver_config:
            image: centos:7
            platform: centos
  
verifier:
  name: serverspec

suites:
  - name: default
    verifier:
      patterns:
        - test/integration/default/serverspec/default_spec.rb
      bundler_path: '/usr/local/bin'
      rspec_path: '/usr/local/bin'
